# Generated by Django 5.0.1 on 2024-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
